server:
  port: 8089

spring:
  application:
    name: other-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - HEAD
              - OPTIONS
      routes:
        - id: adminlogin
          uri: http://localhost:8081/
          predicates:
            - Path=/adminusers,/adminusers/login
          filters:
            - PrefixPath=/privilege
        - id: adminusers
          uri: http://localhost:8081/
          predicates:
            - Path=/adminusers/**,/shops/{shopid}/adminusers/**,/proxies/**,/shops/{shopid}/proxies/**,/shops/{shopid}/roles/**,/shops/{shopid}/roleprivileges/**,/privileges/**,/roles/**,/roles,/shops/{shopid}/roles
          filters:
            - PrefixPath=/privilege
            - Auth=authorization
        - id: userregist
          uri: http://localhost:9999
          predicates:
            - Path=/users
            - Method=POST
        - id: userlogin
          uri: http://localhost:9999
          predicates:
            - Path=/users/login
        - id: share
          uri: http://localhost:9999
          predicates:
            - Path=/skus/{id}/shares,/shares,/shops/{did}/skus/{id}/shares,/beshared,/shops/{did}/skus/{id}/beshared,/shops/{shopId}/skus/{id}/shareactivities,/shareactivities,/shops/{shopId}/shareactivities/{id},/shops/{shopId}/shareactivities/{id},/shops/{shopId}/shareactivities/{id}/online
          filters:
            - PrefixPath=/share
            - Auth=authorization
        - id: userWithToken
          uri: http://localhost:9999
          predicates:
            - Path=/users,/users/password,/usr/all,/user/logout,/users/{id},/shops/{did}/users/{id}/ban,/shops/{did}/users/{id}/release
          filters:
            - Auth=authorization
        - id: userWithToken
          uri: http://localhost:9999
          predicates:
            - Path=/users/states,/users/password/reset
        - id: aftersaleWithToken
          uri: http://localhost:9999
          predicates:
            - Path=/orderItems/{id}/aftersales,/aftersales,/shops/{id}/aftersales,/aftersales/{id},/aftersales/{id}/sendback,/aftersale/{id}/confirm,/shops/{shopId}/aftersales/{id},/shops/{shopId}/aftersales/{id}/confirm,/shops/{shopId}/aftersales/{id}/receive,/shops/{shopId}/aftersales/{id}/deliver
          filters:
            - Auth=authorization
        - id: aftersaleWithoutToken
          uri: http://localhost:9999
          predicates:
            - Path=/aftersales/states
management:
  endpoint:
    gateway:
      enabled: true