server:
  port: 8089

other-ip: localhost:9999
order-ip: 1.2.3.4
gateway:
  activity: http://localhost:8988/
  goods: http://localhost:8907/
  falshsale: http://localhost:8188/


spring:
  application:
    name: other-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - HEAD
              - OPTIONS
      routes:
        - id: adminuserlogin
          uri: http://localhost:8081/
          predicates:
            - Path=/adminusers,/adminusers/login
          filters:
            - PrefixPath=/privilege
        - id: adminusers
          uri: http://localhost:8081/
          predicates:
            - Path=/adminusers/**,/shops/{shopid}/adminusers/**,/proxies/**,/shops/{shopid}/proxies/**,/shops/{shopid}/roles/**,/shops/{shopid}/roleprivileges/**,/privileges/**,/roles/**,/roles,/shops/{shopid}/roles
          filters:
            - PrefixPath=/privilege
            - Auth=authorization
        - id: userregist
          uri: http://${other-ip}
          predicates:
            - Path=/users
            - Method=POST
        - id: userlogin
          uri: http://${other-ip}
          predicates:
            - Path=/users/login
        - id: share
          uri: http://${other-ip}
          predicates:
            - Path=/skus/{id}/shares,/shares,/shops/{did}/skus/{id}/shares,/breshared,/shops/{did}/skus/{id}/beshared,/shops/{shopId}/skus/{id}/shareactivities,/shareactivities,/shops/{shopId}/shareactivities/{id},/shops/{shopId}/shareactivities/{id},/shops/{shopId}/shareactivities/{id}/online
          filters:
            - PrefixPath=/share
            - Auth=authorization
        - id: footprint
          uri: http://${other-ip}
          predicates:
            - Path=/shops/{did}/footprints
          filters:
            - Auth=authorization
        - id: address
          uri: http://${other-ip}
          predicates:
            - Path=/addresses,/addresses/{id}/default,/addresses/{id},/region/{id}/ancestor,/shops/{did}/regions/{id}/subregions,/shops/{did}/regions/{id}
          filters:
            - Auth=authorization
        - id: userWithToken
          uri: http://${other-ip}
          predicates:
            - Path=/users,/users/password,/usr/all,/user/logout,/users/{id},/shops/{did}/users/{id}/ban,/shops/{did}/users/{id}/release
          filters:
            - Auth=authorization
        - id: userWithToken
          uri: http://${other-ip}
          predicates:
            - Path=/users/states,/users/password/reset
        - id: aftersaleWithToken
          uri: http://${other-ip}
          predicates:
            - Path=/orderItems/{id}/aftersales,/aftersales,/shops/{id}/aftersales,/aftersales/{id},/aftersales/{id}/sendback,/aftersale/{id}/confirm,/shops/{shopId}/aftersales/{id},/shops/{shopId}/aftersales/{id}/confirm,/shops/{shopId}/aftersales/{id}/receive,/shops/{shopId}/aftersales/{id}/deliver
          filters:
            - Auth=authorization
        - id: aftersaleWithoutToken
          uri: http://${other-ip}
          predicates:
            - Path=/aftersales/states
        - id: admin-freight
            uri: http://${order-ip}
            predicates:
              - Path=/freightmodels/**,/shops/{id}/freightmodels,/shops/{shopId}/freightmodels/{id}/**,/shops/{shopId}/freightmodels/{id},/shops/{shopId}/freightmodels/{id}/weightItems,/shops/{shopId}/freightmodels/{id}/**,/shops/{shopId}/pieceItems/{id},/shops/{shopId}/weightItems/{id},/shops/{shopId}/freightmodels/{id}
            filters:
              - Auth=authorization

        - id: customer-freight
          uri: http://${order-ip}
          predicates:
            - Path=/region/{rid}/price
          filters:
            - Auth=authorization
            -
        - id: all-order
            uri: http://${order-ip}
            predicates:
              - Path=/orders/states

        - id: customer-order
          uri: http://${order-ip}
          predicates:
            - Path=/orders,/orders/{id},/orders/{id}/confirm,/orders/{id}/groupon-normal
          filters:
            - Auth=authorization

        - id: admin-order
          uri: http://${order-ip}
          predicates:
            - Path=/shops/{shopId}/orders,/shops/{shopId}/orders/{id},/shops/{shopId}/orders/{id}/deliver
          filters:
            - Auth=authorization

        - id: all-payment
            uri: http://${order-ip}
            predicates:
              - Path=/payments/status,/payments/patterns

        - id: customer-payment
            uri: http://${order-ip}
            predicates:
              - Path=/orders/{id}/payments,/aftersales​/{id}​/payments,/orders/{id}/refunds,/aftersales/{id}/refunds
            filters:
              - Auth=authorization

        - id: admin-payment
            uri: http://${order-ip}
            predicates:
              - Path=/shops/{shopId}/orders/{id}/payments,/shops/{shopId}/aftersales/{id}/payments,/shops/{shopId}/orders/{id}/refunds,/shops/{shopId}/aftersales/{id}/refunds
            filters:
              - Auth=authorization

        - id: presale
            uri: ${gateway.activity}
            predicates:
              - Path=/presales/states,/presales,/shops/{shopId}/skus/{id}/presales,/shops/{shopId}/presales/{id},/shops/{shopId}/presales,/shops/{shopId}/presales/{id}/**
            filters:
              - PrefixPath=/presale

        - id: shop
          uri: ${gateway.goods}
          predicates:
            - Path=/shops/states,/shops,/shops/{id},/shops/{shopId}/newshops/{id}/audit,/shops/{id}/onshelves,/shops/{id}/offshelves
          filters:
            - PrefixPath=/shop

        - id: falshsale
          uri: ${gateway.falshsale}
          predicates:
            - Path=/timesegments/{id}/flashsales,/flashsales/current,/shops/{did}/timesegments/{id}/flashsales,/shops/{did}/flashsales/{id},/shops/{did}/flashsales/{id}/flashitems,/shops/{did}/flashsales/{fid}/flashitems/{id},/shops/{did}/flashsales/{id}/**
          filters:
            - PrefixPath=/flashsale

        - id: coupon
          uri: ${gateway.activity}
          predicates:
            - Path=/coupons/states,/shops/{shopId}/couponactivities,/shops/{shopId}/couponactivities/{id}/uploadImg,/couponactivities,/shops/{id}/couponactivities/invalid,/couponactivities/{id}/skus,/shops/{shopId}/couponactivities/{id},/shops/{shopId}/couponactivities/{id}/skus,/shops/{shopId}/couponskus/{id},/coupons,/couponactivities/{id}/usercoupons,/shops/{shopId}/couponactivities/{id}/onshelves,/shops/{shopId}/couponactivities/{id}/offshelves
          filters:
            - PrefixPath=/coupon

        - id: groupon
          uri: ${gateway.activity}
          predicates:
            - Path=/groupons/states,/groupons,/shops/{id}/groupons,/shops/{shopId}/spus/{id}/groupons,/shops/{shopId}/groupons/{id},/shops/{shopId}/groupons/{id}/onshelves,/shops/{shopId}/groupons/{id}/offshelves
          filters:
            - PrefixPath=/groupon

        - id: comment
          uri: ${gateway.goods}
          predicates:
            - Path=/comments/states,/orderitems/{id}/comments,/skus/{id}/comments,/shops/{did}/comments/{id}/confirm,/comments,/shops/{id}/comments/all
          filters:
            - PrefixPath=/comment

        - id: goods
          uri: ${gateway.goods}
          predicates:
            - Path=/skus/states,/skus,/brands,/shops/{shopId}/brands/**,/skus/**,/spus/**,/shops/{shopId}/floatPrices/**,/shops/{shopId}/spus/**,/shops/{shopId}/skus/**,/categories/{id}/subcategories,/shops/{shopId}/categories/**
          filters:
            - PrefixPath=/goods

management:
  endpoint:
    gateway:
      enabled: true